### ISSUE TITLE
Is this library still working / functional?

### ISSUE THREAD

**Issue by Snowlav** [oozie/pyhumod#14]
Hey all!

I'm working on a project where I'd like to use a GSM modem / dongle to act as a proxy server through python.
At my current provider, whenever I disconnect and reconnect to the mobile network, my IP changes.

My goal is to replicate that in python, connecting to the dongle whenever a proxy is needed and disconnecting + reconnecting whenever I need it changed.

If anyone could let me know, that would be great.
Huawei dongles are pretty expensive and hard to come by around here so I'd like to be sure before purchasing one!

Thanks!

**Comment by fmalina** [comment]
Yes, fully functional and tested on Python 3.

**Comment by Snowlav** [comment]
Awesome! Although I am in python 2.7, will that cause any issues ?

> Yes, fully functional and tested on Python 3.
>

**Comment by fmalina** [comment]
The reverse compatibility with 2.7 is still maintained, although you are advised to use latest Python.
